const services=[
["🦷","Dental Checkup","Complete oral examination and preventive care."],["✨","Teeth Cleaning","Gentle professional cleaning for a fresh smile."],["☀️","Teeth Whitening","Professional whitening care for a brighter smile."],["❤️","Root Canal Treatment","Careful treatment designed to save infected teeth."],["🦷","Dental Fillings","Natural-looking fillings for damaged or decayed teeth."],["✓","Dental Implants","Long-term tooth replacement planning."],["⚡","Braces & Aligners","Modern options for straighter teeth."],["💉","Tooth Extraction","Safe extraction when clinically necessary."],["👶","Pediatric Dentistry","Friendly dental care for children."],["✨","Smile Makeover","Personalized cosmetic dental care."],["💧","Gum Treatment","Care for gum health and periodontal problems."],["🏆","Crowns & Bridges","Restore strength, function and appearance."]
];
const reasons=[["🏆","Experienced Dentist","Patient-first care and careful treatment planning."],["⚡","Latest Technology","Modern equipment supporting precision and comfort."],["✓","Affordable Pricing","Clear treatment plans and communication."],["❤️","Pain-Free Approach","Gentle, comfort-focused treatment."],["⏰","Emergency Care","Prompt guidance for urgent dental concerns."],["🛡️","Sterilized Equipment","Strict hygiene and sterilization protocols."],["👤","Personalized Care","Recommendations tailored to each patient."],["😊","Friendly Staff","A welcoming experience from arrival to follow-up."]];
document.getElementById("serviceCards").innerHTML=services.map(s=>`<article class="card reveal"><div class="icon">${s[0]}</div><h3>${s[1]}</h3><p>${s[2]}</p><button onclick="location.hash='appointment'">Learn More →</button></article>`).join("");
document.getElementById("whyCards").innerHTML=reasons.map(s=>`<article class="card reveal"><div class="icon">${s[0]}</div><h3>${s[1]}</h3><p>${s[2]}</p></article>`).join("");
document.querySelector('select[name="service"]').innerHTML='<option value="">Choose a service</option>'+services.map(s=>`<option>${s[1]}</option>`).join("");
document.getElementById("date").min=new Date().toISOString().split("T")[0];

const reviews=[["Priya Sharma","Dr. Richa is extremely gentle and professional. Highly recommended."],["Rahul Verma","The clinic is clean and modern. My treatment was painless."],["Sneha Gupta","Best dental clinic in the city."],["Amit Jain","I got my smile makeover done and the results are amazing."]];
let reviewIndex=0;
function showReview(){document.getElementById("reviewText").textContent=`“${reviews[reviewIndex][1]}”`;document.getElementById("reviewName").textContent=reviews[reviewIndex][0]}
function nextReview(){reviewIndex=(reviewIndex+1)%reviews.length;showReview()}function prevReview(){reviewIndex=(reviewIndex-1+reviews.length)%reviews.length;showReview()}showReview();setInterval(nextReview,5000);

const menuBtn=document.getElementById("menuBtn"),nav=document.getElementById("navLinks");menuBtn.onclick=()=>nav.classList.toggle("open");document.querySelectorAll("#navLinks a").forEach(a=>a.onclick=()=>nav.classList.remove("open"));
document.getElementById("themeBtn").onclick=()=>{document.body.classList.toggle("dark");document.getElementById("themeBtn").textContent=document.body.classList.contains("dark")?"☀":"☾"};

function openChat(){document.getElementById("chat").classList.remove("hidden")}function closeChat(){document.getElementById("chat").classList.add("hidden")}
function askAI(q){const body=document.getElementById("chatBody");body.innerHTML+=`<div class="msg user">${q}</div>`;let a="For a personalized answer, please book an appointment with Dr. Richa.";const x=q.toLowerCase();if(x.includes("tim"))a="Clinic hours are Mon–Sat, 9:00 AM–7:00 PM. Please confirm availability before visiting.";if(x.includes("pain"))a="For severe pain, swelling, trauma or another urgent concern, contact a dental professional promptly.";if(x.includes("root"))a="A root canal may help treat an infected or inflamed tooth and save it. Dr. Richa can assess whether it is appropriate.";if(x.includes("brace"))a="Braces and clear aligners can move teeth gradually. The best option depends on your bite and treatment needs.";if(x.includes("clean"))a="Professional cleaning removes plaque and tartar that regular brushing cannot fully remove.";if(x.includes("whiten"))a="Professional whitening can brighten natural teeth. A dental checkup first is recommended.";setTimeout(()=>{body.innerHTML+=`<div class="msg bot">${a}</div>`;body.scrollTop=body.scrollHeight},450)}

const EMAILJS_PUBLIC_KEY="";const EMAILJS_SERVICE_ID="";const EMAILJS_TEMPLATE_ID="";
if(EMAILJS_PUBLIC_KEY)emailjs.init({publicKey:EMAILJS_PUBLIC_KEY});
document.getElementById("appointmentForm").addEventListener("submit",async e=>{
 e.preventDefault();const form=e.currentTarget,status=document.getElementById("formStatus"),btn=document.getElementById("submitBtn");
 if(!EMAILJS_PUBLIC_KEY||!EMAILJS_SERVICE_ID||!EMAILJS_TEMPLATE_ID){status.className="error";status.textContent="EmailJS is not configured. Add your Public Key, Service ID and Template ID in script.js, then submit again.";return}
 if(btn.disabled)return;btn.disabled=true;btn.textContent="Sending...";
 const now=new Date();const params={name:form.name.value,phone:form.phone.value,email:form.email.value,age:form.age.value,gender:form.gender.value,service:form.service.value,date:form.date.value,time:form.time.value,message:form.message.value,current_date:now.toLocaleDateString("en-IN"),current_time:now.toLocaleTimeString("en-IN")};
 try{await emailjs.send(EMAILJS_SERVICE_ID,EMAILJS_TEMPLATE_ID,params);status.className="success";status.textContent="Thank you! Your appointment request has been received. We will contact you shortly.";form.reset()}catch(err){console.error(err);status.className="error";status.textContent="We couldn't send the request right now. Please try again or call the clinic."}finally{btn.disabled=false;btn.textContent="Book Appointment →"}
});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("show")}),{threshold:.1});document.querySelectorAll(".reveal").forEach(x=>observer.observe(x));